pub const LEETCODE_JSON_URL: &str = "https://leetcode.com/api/problems/algorithms/";
pub const LEETCODE_TAG_URL: &str = "https://leetcode.com/problems/api/tags/";
pub const LEETCODE_QUESTION_URL: &str = "https://leetcode.com/problems/";
pub const CARGO_MANIFEST_DIR: &str = "CARGO_MANIFEST_DIR";
pub const README_MD: &str = "README.md";
pub const LEETCODE_SRC: &str = "rustgym/src/leetcode";
pub const LEETCODE_DESC: &str = "rustgym/desc/leetcode";
// pub const HACKERRANK_SRC: &str = "rustgym/src/hackerrank";
// pub const HACKERRANK_DESC: &str = "rustgym/desc/hackerrank";
